#mongodb+srv://khushi4221:khushi220201@cluster0.uddjv5y.mongodb.net/microservices
server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb+srv://khushi4221:khushi220201@cluster0.uddjv5y.mongodb.net
      database: microservices

  application:
    name: RATING-SERVICES

  config:
    import: optional:configserver:http://localhost:8085
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka