#mongodb+srv://khushi4221:khushi220201@cluster0.uddjv5y.mongodb.net/microservices
server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb+srv://khushi4221:khushi220201@cluster0.uddjv5y.mongodb.net
      database: microservices