server:
  port: 8085


spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/veer4221/microservice-configuration
          clone-on-start: true