server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3397/microServicePoc
    username: root
    password: $$awsVeer4221
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update